spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: smart-task-management
  datasource:
    url : jdbc:postgresql://localhost:5432/smart_tasks
    username : admin
    password : admin
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        multi_tenant: SCHEMA
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
  threads:
    virtual:
      enabled: true
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:${GOOGLE_API_KEY:}}
        chat:
          options:
            model: gemini-2.5-flash
server:
  port: 8082
